# This is a sample input.conf file. You may edit this file as you desire to change MPV's input commands. See the input.conf.md file for more info

# i    script-binding stats/display-stats
# I    script-binding stats/display-stats-toggle
# F1   script-binding stats/display-page-1
# F2   script-binding stats/display-page-2
# F3   script-binding stats/display-page-3
# F4   script-binding stats/display-page-4
