#!/usr/bin/env bash
# Regenerates toolbar.ts from the live Glide profile. Rearrange the toolbar in
# the UI (right-click, Customize Toolbar), then run this to record the layout.
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import json
import re
from pathlib import Path

profiles = Path.home() / 'Library/Application Support/glide/Profiles'
candidates = sorted(
    profiles.glob('*/prefs.js'), key=lambda p: p.stat().st_mtime, reverse=True
)

for prefs in candidates:
    match = re.search(
        r'user_pref\("browser\.uiCustomization\.state", "(.*)"\);',
        prefs.read_text(),
    )
    if match:
        break
else:
    raise SystemExit('no Glide profile has browser.uiCustomization.state')

# The pref value is JSON wrapped in a JS string literal, so decode twice.
state = json.loads(json.loads(f'"{match.group(1)}"'))

header = '''\
/**
 * Toolbar layout: which buttons are where, spacers, pinned/removed items.
 *
 * Firefox Sync has never synced this. The layout lives in the
 * `browser.uiCustomization.state` pref, which sync excludes, so pinning it
 * here is what makes a fresh machine come up with the same chrome.
 *
 * Generated by ./export-toolbar.sh from the most recently used profile: edit
 * the toolbar in the UI, then run that script to record the change. Applies
 * on startup; a running instance may need a restart to pick it up.
 */

const state = '''

body = json.dumps(state, indent=2)

footer = ''';

glide.prefs.set('browser.uiCustomization.state', JSON.stringify(state));
'''

Path('toolbar.ts').write_text(header + body + footer)
print(f'toolbar.ts written from {prefs}')
PY
