/**
 * Toolbar layout: which buttons are where, spacers, pinned/removed items.
 *
 * Firefox Sync has never synced this. The layout lives in the
 * `browser.uiCustomization.state` pref, which sync excludes, so pinning it
 * here is what makes a fresh machine come up with the same chrome.
 *
 * Generated by ./export-toolbar.sh from the most recently used profile: edit
 * the toolbar in the UI, then run that script to record the change. Applies
 * on startup; a running instance may need a restart to pick it up.
 */

const state = {
  "placements": {
    "widget-overflow-fixed-list": [
      "downloads-button",
      "fxa-toolbar-menu-button",
      "firefox-view-button",
      "alltabs-button",
      "sidebar-button"
    ],
    "unified-extensions-area": [
      "_d634138d-c276-4fc8-924b-40a0ea21d284_-browser-action",
      "neaturl_hugsmile_eu-browser-action",
      "gdpr_cavi_au_dk-browser-action",
      "_a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad_-browser-action",
      "_7599bb55-1e8e-445a-9e32-66da6e1d6749_-browser-action",
      "_8e8191f9-877a-45a0-b186-b5e83e98b7e9_-browser-action",
      "87677a2c52b84ad3a151a4a72f5bd3c4_jetpack-browser-action",
      "firefoxcolor_mozilla_com-browser-action"
    ],
    "nav-bar": [
      "back-button",
      "forward-button",
      "vertical-spacer",
      "urlbar-container",
      "reset-pbm-toolbar-button",
      "unified-extensions-button"
    ],
    "TabsToolbar": [
      "tabbrowser-tabs",
      "glide-toolbar-mode-button"
    ],
    "vertical-tabs": [],
    "PersonalToolbar": [
      "import-button",
      "personal-bookmarks"
    ]
  },
  "seen": [
    "reset-pbm-toolbar-button",
    "developer-button",
    "screenshot-button",
    "neaturl_hugsmile_eu-browser-action",
    "gdpr_cavi_au_dk-browser-action",
    "_a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad_-browser-action",
    "_7599bb55-1e8e-445a-9e32-66da6e1d6749_-browser-action",
    "_8e8191f9-877a-45a0-b186-b5e83e98b7e9_-browser-action",
    "87677a2c52b84ad3a151a4a72f5bd3c4_jetpack-browser-action",
    "_d634138d-c276-4fc8-924b-40a0ea21d284_-browser-action",
    "firefoxcolor_mozilla_com-browser-action",
    "ipprotection-button"
  ],
  "dirtyAreaCache": [
    "nav-bar",
    "vertical-tabs",
    "PersonalToolbar",
    "TabsToolbar",
    "widget-overflow-fixed-list",
    "unified-extensions-area"
  ],
  "currentVersion": 24,
  "newElementCount": 8
};

glide.prefs.set('browser.uiCustomization.state', JSON.stringify(state));
